<a href="https://colab.research.google.com/github/erlangpr/pd6_terapan/blob/main/pd_6(Ei_Deca_Pratama).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel ("Data_Alumni1.xlsx", 0)

In [ ]:
df.isna().sum()

No                      0
NIM                     0
NAMA                    0
TTL                     0
FAKULTAS/KETRAMPILAN    0
ALAMAT                  0
TH.MASUK                0
TH.LULUS                0
STATUS                  0
MASA_TUNGGU             0
GAJI                    0
TOEFL                   0
IPK                     0
dtype: int64

In [ ]:
data = df.dropna()

In [ ]:
data

,No,NIM,NAMA,TTL,FAKULTAS/KETRAMPILAN,ALAMAT,TH.MASUK,TH.LULUS,STATUS,MASA_TUNGGU,GAJI,TOEFL,IPK
0,1,9018263,Puguh Drajat E.P,"Purworejo, 4 November 1989",FTI / Teknik Iformatika,Tangerang Rt. 01/ 0,2009,2016,Mahasiswa,2.4,1.475635e+06,390.0,2.13
3,4,9018269,Pandu Herwijaya,"Lampung, 19 Desember 1990",FTI/ Teknik Infomatika,"Tamantirto, Kasihan ,Bantul",2009,2016,Mahasiswa,2.4,1.475634e+06,413.0,2.75
5,6,9020026,Moh. Dadi Kurniawan,"Savanajaya, 27 Maret 1992",FTI / Futsal,Saren Rt. 02 Rw. 01 Caturtunggal,2009,2016,Mahasiswa,2.4,1.475635e+06,400.0,3.24
6,7,12018060,Martin Sarlina,"Lepak, 23 Maret 1994",FTI,NTB,2012,2016,Mahasiswa,2.4,1.475635e+06,396.0,3.27
7,8,11018022,Yan Adhi Permadi,"Jepara, 22 juni 1993",FTI,Umbulharjo V,2011,2016,Wiraswasta,2.4,1.475635e+06,460.0,3.20
8,9,9018212,Achicha Wahyuni,"Yogyakarta, 3 juni 1991",FTI/ Web Design,"Noyokerten, Sendangirto, Berbah",2009,2016,Guru,0.0,6.000000e+05,403.0,3.24
9,10,9018301,Yayan Tisna Permadi,"Purbalingga, 08 Oktober 1991",FTI/ Teknik Inormatika,"Tajug, Rt.04/ 05 Purbalingga",2009,2016,Mahasiswa,2.4,1.475635e+06,450.0,3.06
10,11,12022020,Muh. Rama dhai,"Pekanbaru, 29 Maret 1992",FTI / Teknik Elektro,"Karongan Rt/Rw. 04/11 Jogotirto, Berbah Sleman",2012,2016,Mahasiswa,2.4,1.200000e+06,423.0,3.47
11,12,12022038,Nurwahyuddi,"Dili, timor-timur/ 13 April 1995",FTI / Teknik Elektro,Juru Gentong J V/407 C Banguntapan,2012,2016,Mahasiswa,2.4,1.475635e+06,413.0,3.62
12,13,12019039,Agus Purnomo,"Klaten, 2 Agustus 1992",FTI/ Teknik Industri,"Dukuh Glagahwangi, Polanharjo",2012,2016,Mahasiswa,2.4,1.475635e+06,480.0,3.32
13,14,11018111,M. Akhwan Zulfayandi,"Teros, 12 September 1992",FTI/ Teknik Informatika,"Jl. Peumnas gg. Indragiri Blok B/24, Condongcatur",2011,2016,Mahasiswa,2.4,1.475635e+06,406.0,3.14
14,15,9018135,Yunita Tri Hernawai,"Magelang, 20 Juni 1991",FTI/ Teknik Informatika,Magelang,2009,2016,Swasta,1.0,1.500000e+06,423.0,2.99
15,16,12018161,Pratama Setya Aji,"Sleman, 20 September 1994",FTI,Jl. Affandi gg.Kamboja CTX.19 Yogyakarta,2012,2016,Freelance,0.0,7.500000e+05,400.0,3.60

**Pembersihan data menggunakan *mean value.***

In [ ]:
mean_toefl = data.TOEFL.mean()

In [ ]:
mean_toefl

419.7692307692308

In [ ]:
mean_ipk = data.IPK.mean()

In [ ]:
mean_ipk

3.1561538461538463

In [ ]:
mean_gaji = data.GAJI.mean()

In [ ]:
mean_gaji

1333131.609467457

In [ ]:
mean_masatunggu = data.MASA_TUNGGU.mean()

In [ ]:
mean_masatunggu

1.9230769230769225

In [ ]:
max_ipk = data.IPK.max()

In [ ]:
data.IPK.max()

3.62

In [ ]:
data.IPK.min()

2.99

In [ ]:
data.GAJI.min()

600000.0

In [ ]:
data.MASA_TUNGGU.max()

2.4

In [ ]:
data.TOEFL.max()

480.0

**Pembersihan data menggunakan *don’t care method.***

In [ ]:
def_status = 'Mahasiswa'
df.STATUS.fillna(def_status, inplace = True)
df

,No,NIM,NAMA,TTL,FAKULTAS/KETRAMPILAN,ALAMAT,TH.MASUK,TH.LULUS,STATUS,MASA TUNGGU,GAJI,TOEFL,IPK
0,1,9018263,Puguh Drajat E.P,"Purworejo, 4 November 1989",FTI / Teknik Iformatika,Tangerang Rt. 01/ 0,2009,2016,Mahasiswa,2.4,1.475635e+06,390.0,2.13
1,2,12022030,Arsyad Cahya Subrata,"Bantul, 21 juni 1994",FTI / Teknik Elektro,"Karangpule Rt.01 , Tirtonirmolo , Kasihan Bantul",2012,2016,Mahasiswa,NaN,NaN,NaN,NaN
2,3,12020021,Yesi Novela,"Tempilang, 1 januari 1995",FTI,NaN,2012,2016,Mahasiswa,2.4,1.475635e+06,NaN,NaN
3,4,9018269,Pandu Herwijaya,"Lampung, 19 Desember 1990",FTI/ Teknik Infomatika,"Tamantirto, Kasihan ,Bantul",2009,2016,Mahasiswa,2.4,1.475634e+06,413.0,2.75
4,5,9018109,Anjar Prasetyo,"Gunungkidul, 27 April 1991",FTI /Teknik Informatika,"Umbulharjo , Yogyakarta",2009,2016,Mahasiswa,NaN,NaN,NaN,NaN
5,6,9020026,Moh. Dadi Kurniawan,"Savanajaya, 27 Maret 1992",FTI / Futsal,Saren Rt. 02 Rw. 01 Caturtunggal,2009,2016,Mahasiswa,2.4,1.475635e+06,400.0,3.24
6,7,12018060,Martin Sarlina,"Lepak, 23 Maret 1994",FTI,NTB,2012,2016,Mahasiswa,2.4,1.475635e+06,396.0,3.27
7,8,11018022,Yan Adhi Permadi,"Jepara, 22 juni 1993",FTI,Umbulharjo V,2011,2016,Wiraswasta,2.4,1.475635e+06,460.0,3.20
8,9,9018212,Achicha Wahyuni,"Yogyakarta, 3 juni 1991",FTI/ Web Design,"Noyokerten, Sendangirto, Berbah",2009,2016,Guru,0.0,6.000000e+05,403.0,3.24
9,10,9018301,Yayan Tisna Permadi,"Purbalingga, 08 Oktober 1991",FTI/ Teknik Inormatika,"Tajug, Rt.04/ 05 Purbalingga",2009,2016,Mahasiswa,2.4,1.475635e+06,450.0,3.06
10,11,12022020,Muh. Rama dhai,"Pekanbaru, 29 Maret 1992",FTI / Teknik Elektro,"Karongan Rt/Rw. 04/11 Jogotirto, Berbah Sleman",2012,2016,Mahasiswa,2.4,1.200000e+06,423.0,3.47
11,12,12022038,Nurwahyuddi,"Dili, timor-timur/ 13 April 1995",FTI / Teknik Elektro,Juru Gentong J V/407 C Banguntapan,2012,2016,Mahasiswa,2.4,1.475635e+06,413.0,3.62
12,13,12019039,Agus Purnomo,"Klaten, 2 Agustus 1992",FTI/ Teknik Industri,"Dukuh Glagahwangi, Polanharjo",2012,2016,Mahasiswa,2.4,1.475635e+06,480.0,3.32
13,14,11018111,M. Akhwan Zulfayandi,"Teros, 12 September 1992",FTI/ Teknik Informatika,"Jl. Peumnas gg. Indragiri Blok B/24, Condongcatur",2011,2016,Mahasiswa,2.4,1.475635e+06,406.0,3.14
14,15,9018135,Yunita Tri Hernawai,"Magelang, 20 Juni 1991",FTI/ Teknik Informatika,Magelang,2009,2016,Swasta,1.0,1.500000e+06,423.0,2.99
15,16,12018161,Pratama Setya Aji,"Sleman, 20 September 1994",FTI,Jl. Affandi gg.Kamboja CTX.19 Yogyakarta,2012,2016,Freelance,0.0,7.500000e+05,400.0,3.60

In [ ]:
from google.colab import files
df.to_csv('PD_6.csv')
files.download('pd_6.csv')

In [ ]:
df.isna().sum()

No                      0
NIM                     0
NAMA                    0
TTL                     0
FAKULTAS/KETRAMPILAN    0
ALAMAT                  0
TH.MASUK                0
TH.LULUS                0
STATUS                  0
MASA_TUNGGU             0
GAJI                    0
TOEFL                   0
IPK                     0
dtype: int64

In [ ]:
data = df.dropna()
data

,No,NIM,NAMA,TTL,FAKULTAS/KETRAMPILAN,ALAMAT,TH.MASUK,TH.LULUS,STATUS,MASA_TUNGGU,GAJI,TOEFL,IPK
0,1,9018263,Puguh Drajat E.P,"Purworejo, 4 November 1989",FTI / Teknik Iformatika,Tangerang Rt. 01/ 0,2009,2016,Mahasiswa,2.4,1.475635e+06,390,2.13
1,2,12022030,Arsyad Cahya Subrata,"Bantul, 21 juni 1994",FTI / Teknik Elektro,"Karangpule Rt.01 , Tirtonirmolo , Kasihan Bantul",2012,2016,Mahasiswa,1.9,1.331310e+05,419,3.15
2,3,12020021,Yesi Novela,"Tempilang, 1 januari 1995",FTI,Banyuwangi,2012,2016,Mahasiswa,2.4,1.475635e+06,419,3.15
3,4,9018269,Pandu Herwijaya,"Lampung, 19 Desember 1990",FTI/ Teknik Infomatika,"Tamantirto, Kasihan ,Bantul",2009,2016,Mahasiswa,2.4,1.475634e+06,413,2.75
4,5,9018109,Anjar Prasetyo,"Gunungkidul, 27 April 1991",FTI /Teknik Informatika,"Umbulharjo , Yogyakarta",2009,2016,Mahasiswa,1.9,1.331310e+05,419,3.15
5,6,9020026,Moh. Dadi Kurniawan,"Savanajaya, 27 Maret 1992",FTI / Futsal,Saren Rt. 02 Rw. 01 Caturtunggal,2009,2016,Mahasiswa,2.4,1.475635e+06,400,3.24
6,7,12018060,Martin Sarlina,"Lepak, 23 Maret 1994",FTI,NTB,2012,2016,Mahasiswa,2.4,1.475635e+06,396,3.27
7,8,11018022,Yan Adhi Permadi,"Jepara, 22 juni 1993",FTI,Umbulharjo V,2011,2016,Wiraswasta,2.4,1.475635e+06,460,3.20
8,9,9018212,Achicha Wahyuni,"Yogyakarta, 3 juni 1991",FTI/ Web Design,"Noyokerten, Sendangirto, Berbah",2009,2016,Guru,0.0,6.000000e+05,403,3.24
9,10,9018301,Yayan Tisna Permadi,"Purbalingga, 08 Oktober 1991",FTI/ Teknik Inormatika,"Tajug, Rt.04/ 05 Purbalingga",2009,2016,Mahasiswa,2.4,1.475635e+06,450,3.06
10,11,12022020,Muh. Rama dhai,"Pekanbaru, 29 Maret 1992",FTI / Teknik Elektro,"Karongan Rt/Rw. 04/11 Jogotirto, Berbah Sleman",2012,2016,Mahasiswa,2.4,1.200000e+06,423,3.47
11,12,12022038,Nurwahyuddi,"Dili, timor-timur/ 13 April 1995",FTI / Teknik Elektro,Juru Gentong J V/407 C Banguntapan,2012,2016,Mahasiswa,2.4,1.475635e+06,413,3.62
12,13,12019039,Agus Purnomo,"Klaten, 2 Agustus 1992",FTI/ Teknik Industri,"Dukuh Glagahwangi, Polanharjo",2012,2016,Mahasiswa,2.4,1.475635e+06,480,3.32
13,14,11018111,M. Akhwan Zulfayandi,"Teros, 12 September 1992",FTI/ Teknik Informatika,"Jl. Peumnas gg. Indragiri Blok B/24, Condongcatur",2011,2016,Mahasiswa,2.4,1.475635e+06,406,3.14
14,15,9018135,Yunita Tri Hernawai,"Magelang, 20 Juni 1991",FTI/ Teknik Informatika,Magelang,2009,2016,Swasta,1.0,1.500000e+06,423,2.99
15,16,12018161,Pratama Setya Aji,"Sleman, 20 September 1994",FTI,Jl. Affandi gg.Kamboja CTX.19 Yogyakarta,2012,2016,Freelance,0.0,7.500000e+05,400,3.60